/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SSlugRouteImport } from './routes/s/$slug'
import { Route as SPreviewCompanyIdRouteImport } from './routes/s/preview/$companyId'
import { Route as PublicCIdRouteImport } from './routes/public/c/$id'
import { Route as AuthenticatedCNewRouteImport } from './routes/_authenticated/c/new'
import { Route as AuthenticatedCIdRouteImport } from './routes/_authenticated/c/$id'

const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SPreviewCompanyIdRoute = SPreviewCompanyIdRouteImport.update({
  id: '/s/preview/$companyId',
  path: '/s/preview/$companyId',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicCIdRoute = PublicCIdRouteImport.update({
  id: '/public/c/$id',
  path: '/public/c/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCNewRoute = AuthenticatedCNewRouteImport.update({
  id: '/c/new',
  path: '/c/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCIdRoute = AuthenticatedCIdRouteImport.update({
  id: '/c/$id',
  path: '/c/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/s/$slug': typeof SSlugRoute
  '/c/$id': typeof AuthenticatedCIdRoute
  '/c/new': typeof AuthenticatedCNewRoute
  '/public/c/$id': typeof PublicCIdRoute
  '/s/preview/$companyId': typeof SPreviewCompanyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/s/$slug': typeof SSlugRoute
  '/c/$id': typeof AuthenticatedCIdRoute
  '/c/new': typeof AuthenticatedCNewRoute
  '/public/c/$id': typeof PublicCIdRoute
  '/s/preview/$companyId': typeof SPreviewCompanyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/s/$slug': typeof SSlugRoute
  '/_authenticated/c/$id': typeof AuthenticatedCIdRoute
  '/_authenticated/c/new': typeof AuthenticatedCNewRoute
  '/public/c/$id': typeof PublicCIdRoute
  '/s/preview/$companyId': typeof SPreviewCompanyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gallery'
    | '/s/$slug'
    | '/c/$id'
    | '/c/new'
    | '/public/c/$id'
    | '/s/preview/$companyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gallery'
    | '/s/$slug'
    | '/c/$id'
    | '/c/new'
    | '/public/c/$id'
    | '/s/preview/$companyId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/gallery'
    | '/s/$slug'
    | '/_authenticated/c/$id'
    | '/_authenticated/c/new'
    | '/public/c/$id'
    | '/s/preview/$companyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  GalleryRoute: typeof GalleryRoute
  SSlugRoute: typeof SSlugRoute
  PublicCIdRoute: typeof PublicCIdRoute
  SPreviewCompanyIdRoute: typeof SPreviewCompanyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/preview/$companyId': {
      id: '/s/preview/$companyId'
      path: '/s/preview/$companyId'
      fullPath: '/s/preview/$companyId'
      preLoaderRoute: typeof SPreviewCompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/c/$id': {
      id: '/public/c/$id'
      path: '/public/c/$id'
      fullPath: '/public/c/$id'
      preLoaderRoute: typeof PublicCIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/c/new': {
      id: '/_authenticated/c/new'
      path: '/c/new'
      fullPath: '/c/new'
      preLoaderRoute: typeof AuthenticatedCNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/c/$id': {
      id: '/_authenticated/c/$id'
      path: '/c/$id'
      fullPath: '/c/$id'
      preLoaderRoute: typeof AuthenticatedCIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCIdRoute: typeof AuthenticatedCIdRoute
  AuthenticatedCNewRoute: typeof AuthenticatedCNewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCIdRoute: AuthenticatedCIdRoute,
  AuthenticatedCNewRoute: AuthenticatedCNewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  GalleryRoute: GalleryRoute,
  SSlugRoute: SSlugRoute,
  PublicCIdRoute: PublicCIdRoute,
  SPreviewCompanyIdRoute: SPreviewCompanyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
